// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_random_uuid from "./routes/api/random-uuid.ts";
import * as $countdown from "./routes/countdown.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $html from "./routes/html.tsx";
import * as $html2 from "./routes/html2.tsx";
import * as $index from "./routes/index.tsx";
import * as $page from "./routes/page.tsx";
import * as $plain from "./routes/plain.tsx";
import * as $search from "./routes/search.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CounterButton from "./islands/CounterButton.tsx";
import * as $Coutdown from "./islands/Coutdown.tsx";
import * as $JSONFormatter from "./islands/JSONFormatter.tsx";
import * as $TicTacToe from "./islands/TicTacToe.tsx";
import * as $TicTacToe2 from "./islands/TicTacToe2.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/random-uuid.ts": $api_random_uuid,
    "./routes/countdown.tsx": $countdown,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/html.tsx": $html,
    "./routes/html2.tsx": $html2,
    "./routes/index.tsx": $index,
    "./routes/page.tsx": $page,
    "./routes/plain.tsx": $plain,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/CounterButton.tsx": $CounterButton,
    "./islands/Coutdown.tsx": $Coutdown,
    "./islands/JSONFormatter.tsx": $JSONFormatter,
    "./islands/TicTacToe.tsx": $TicTacToe,
    "./islands/TicTacToe2.tsx": $TicTacToe2,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
